name: underwater_static_gaussian_splatting
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.8
  - plyfile
  - python=3.9.13
  - pip=22.2.2
  - tqdm
Do not install these from here. Install manually using pip after creating the conda env in the env
  - pip:
    - torch==1.13.0
    - torchaudio==0.13.0
    - torchvision==0.14.0
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn